name = "portfolio-github-stats"
main = "crates/worker/build/index.js"
compatibility_date = "2024-01-01"

[build]
command = "cargo install worker-build && cd crates/worker && worker-build --release"

# wrangler secret put GITHUB_TOKEN
