name = "portfolio-github-stats"
main = "crates/worker/build/index.js"
compatibility_date = "2024-01-01"

[build]
command = "cargo install worker-build && worker-build --release"
cwd = "crates/worker"
